--Audit Tables
--Last tested on Tableau Server 10.3
SELECT "historical_events"."id" AS "id",
  "historical_events"."historical_event_type_id" AS "historical_event_type_id",
  CAST("historical_events"."worker" AS TEXT) AS "worker",
  "historical_events"."duration_in_ms" AS "duration_in_ms",
  "historical_events"."is_failure" AS "is_failure",
  CAST("historical_events"."details" AS TEXT) AS "details",
  "historical_events"."created_at" AS "created_at",
  "historical_events"."hist_actor_user_id" AS "hist_actor_user_id",
  "historical_events"."hist_target_user_id" AS "hist_target_user_id",
  "historical_events"."hist_actor_site_id" AS "hist_actor_site_id",
  "historical_events"."hist_target_site_id" AS "hist_target_site_id",
  "historical_events"."hist_project_id" AS "hist_project_id",
  "historical_events"."hist_workbook_id" AS "hist_workbook_id",
  "historical_events"."hist_view_id" AS "hist_view_id",
  "historical_events"."hist_datasource_id" AS "hist_datasource_id",
  "historical_events"."hist_comment_id" AS "hist_comment_id",
  "historical_events"."hist_tag_id" AS "hist_tag_id",
  "historical_events"."hist_group_id" AS "hist_group_id",
  "historical_events"."hist_licensing_role_id" AS "hist_licensing_role_id",
  "historical_events"."hist_schedule_id" AS "hist_schedule_id",
  "historical_events"."hist_task_id" AS "hist_task_id",
  "historical_events"."hist_data_connection_id" AS "hist_data_connection_id",
  "historical_events"."hist_config_id" AS "hist_config_id",
  "historical_events"."hist_capability_id" AS "hist_capability_id",
  "historical_event_types"."type_id" AS "type_id",
  CAST("historical_event_types"."name" AS TEXT) AS "name",
  CAST("historical_event_types"."action_type" AS TEXT) AS "action_type",
  "hist_datasources"."id" AS "id (hist_datasources)",
  "hist_datasources"."datasource_id" AS "datasource_id",
  CAST("hist_datasources"."name" AS TEXT) AS "name (hist_datasources)",
  CAST("hist_datasources"."repository_url" AS TEXT) AS "repository_url",
  "hist_datasources"."size" AS "size",
  CAST("hist_datasources"."revision" AS TEXT) AS "revision",
  "hist_datasources"."using_remote_query_agent" AS "using_remote_query_agent",
  CAST("hist_datasources"."remote_query_agent_name" AS TEXT) AS "remote_query_agent_name",
  "hist_workbooks"."id" AS "id (hist_workbooks)",
  "hist_workbooks"."workbook_id" AS "workbook_id",
  CAST("hist_workbooks"."name" AS TEXT) AS "name (hist_workbooks)",
  CAST("hist_workbooks"."repository_url" AS TEXT) AS "repository_url (hist_workbooks)",
  "hist_workbooks"."size" AS "size (hist_workbooks)",
  CAST("hist_workbooks"."revision" AS TEXT) AS "revision (hist_workbooks)",
  "hist_users"."id" AS "id (hist_users)",
  "hist_users"."user_id" AS "user_id",
  CAST("hist_users"."name" AS TEXT) AS "name (hist_users)",
  CAST("hist_users"."domain_name" AS TEXT) AS "domain_name",
  CAST("hist_users"."email" AS TEXT) AS "email",
  "hist_users"."system_user_id" AS "system_user_id",
  "hist_users"."system_admin_level" AS "system_admin_level",
  "hist_users"."hist_licensing_role_id" AS "hist_licensing_role_id (hist_users)",
  "hist_users"."site_admin_level" AS "site_admin_level",
  "hist_users"."publisher_tristate" AS "publisher_tristate",
  "hist_users"."site_role_id" AS "site_role_id",
  "hist_views"."id" AS "id (hist_views)",
  "hist_views"."view_id" AS "view_id",
  CAST("hist_views"."name" AS TEXT) AS "name (hist_views)",
  CAST("hist_views"."repository_url" AS TEXT) AS "repository_url (hist_views)",
  CAST("hist_views"."revision" AS TEXT) AS "revision (hist_views)",
  "hist_sites"."id" AS "id (hist_sites)",
  "hist_sites"."site_id" AS "site_id",
  CAST("hist_sites"."name" AS TEXT) AS "name (hist_sites)",
  CAST("hist_sites"."url_namespace" AS TEXT) AS "url_namespace",
  "hist_comments"."id" AS "id (hist_comments)",
  "hist_comments"."comment_id" AS "comment_id",
  CAST("hist_comments"."comment" AS TEXT) AS "comment",
  "hist_projects"."id" AS "id (hist_projects)",
  "hist_projects"."project_id" AS "project_id",
  CAST("hist_projects"."name" AS TEXT) AS "name (hist_projects)"
FROM "public"."historical_events" "historical_events"
  INNER JOIN "public"."historical_event_types" "historical_event_types" ON ("historical_events"."historical_event_type_id" = "historical_event_types"."type_id")
  LEFT JOIN "public"."hist_datasources" "hist_datasources" ON ("historical_events"."hist_datasource_id" = "hist_datasources"."id")
  LEFT JOIN "public"."hist_workbooks" "hist_workbooks" ON ("historical_events"."hist_workbook_id" = "hist_workbooks"."id")
  LEFT JOIN "public"."hist_users" "hist_users" ON ("historical_events"."hist_actor_user_id" = "hist_users"."id")
  LEFT JOIN "public"."hist_views" "hist_views" ON ("historical_events"."hist_view_id" = "hist_views"."id")
  LEFT JOIN "public"."hist_sites" "hist_sites" ON ("historical_events"."hist_actor_site_id" = "hist_sites"."id")
  LEFT JOIN "public"."hist_comments" "hist_comments" ON ("historical_events"."hist_comment_id" = "hist_comments"."id")
  LEFT JOIN "public"."hist_projects" "hist_projects" ON ("historical_events"."hist_project_id" = "hist_projects"."id")